general.import = [
    "~/.config/alacritty/themes/themes/solarized_dark.toml"
]

[window]
opacity = 0.9


[font]
size = 10.0

[font.bold]
family = "AdwaitaMono Nerd Font"
style = "Bold"

[font.normal]
family = "AdwaitaMono Nerd Font"
style = "Regular"
